path: .
train: images/train
val: images/val

names:
  0: long sleeve top
  1: short sleeve top
  2: vest
  3: skirt
  4: shorts
  5: trousers
  6: long sleeve dress
  7: short sleeve dress
  8: vest dress
